### ISSUE TITLE
Number updates on site

### ISSUE THREAD

**Issue by willpearse** [pearselab/argon#1]
I can't believe how dumb I'm being, but I can't get the JS for the button updates to work. I've modified the numbers in the JS file, but when I click the NATDB/NACDB buttons it won't update. Do you know what's going on @bweedop ? I ask because it would be nice to demo the site in my presentation today!

**Comment by bweedop** [comment]
@willpearse I just tested the buttons in the website and they are working with the new numbers you put  in the js on my end... I'll investigate whether or not it is something with the links to the js file if not

**Comment by willpearse** [comment]
It's working now. I think we should chalk this up to "Will being a moron". Thanks Bodie!!!
